version: 2.1

commands:
  zip_build:
    parameters:
      target:
        type: string
      exec:
        type: string
    steps:
      - run:
          name: "Zip: << parameters.target >>"
          command: |
            cd ./pkg/
            zip shift-code-<< parameters.target >> shift-code-<< parameters.exec >>
      - store_artifacts:
          path: ./pkg/shift-code-<< parameters.target >>.zip
executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - run:
          name: Check
          command: ls -la dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  artifact:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Package
          command: npm run pkg
      - run:
          name: Check
          command: ls -la pkg
      - zip_build:
          target: linux
          exec: linux
      - zip_build:
          target: mac
          exec: macos
      - zip_build:
          target: windows
          exec: win.exe
      - persist_to_workspace:
          root: .
          paths:
            - pkg

  publish:
    executor: node
    steps:
      - run:
          name: Publish
          command: npx semantic-release

workflows:
  version: 2

  publish:
    jobs:
      - install
      - build:
          requires:
            - install
      - artifact:
          requires:
            - build
      - publish:
          requires:
            - artifact
          filters:
            branches:
              only: master